package com.northamptonmedicalclinic.app;

import java.awt.EventQueue;

import com.northamptonmedicalclinic.app.controller.LoginController;
import com.northamptonmedicalclinic.app.models.LoginModel;
import com.northamptonmedicalclinic.app.views.LoginView;

public class Main {

	

	/**
	 * Main Class Generated by the Window Builder, modified under the MVC Pattern.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					final LoginModel model = new LoginModel();
					final LoginController  controller = new LoginController(model);
					final LoginView view = new LoginView(controller, model);
					controller.setView(view);
					view.setVisible(true);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
		
	}
	


	

}
